---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-nonfree-n8n
  namespace: cozy-public
spec:
  chart: ./packages/apps/n8n
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm-nonfree
    namespace: cozy-public
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cozyllm-nonfree-open-webui
  namespace: cozy-public
spec:
  chart: ./packages/apps/open-webui
  interval: 1m
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: cozyllm-nonfree
    namespace: cozy-public
